server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/bet_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          pool_size: 10
          min_pool_size: 1
          max_pool_size: 30
          timeout: 30000
  jta:
    atomikos:
      datasource:
        login-timeout: 30000
        min-pool-size: 1
        max-pool-size: 30
        test-query: SELECT 1
      connectionfactory:
        min-pool-size: 1
        max-pool-size: 3
        max-timeout: 30000
        default-jta-timeout: 30000
jwt:
  access-token-key: '{"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
  refresh-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'